# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'maxhennen'
    scannerMode: 'Other'
    cliProjectKey: 'maxhennen_kwetter'
    projectKey: 'maxhennen_kwetter'
    extraProperties: 'sonar.projectKey=maxhennen_kwetter'
- task: Maven@3
  inputs:
    mavenPomFile: 'Kwetter/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    mavenDirectory: 'Kwetter'
    codeCoverageToolOption: 'None'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: false
    pmdRunAnalysis: false
    findBugsRunAnalysis: false

